/**
 * Seed challenge review data for Contoso Global Web Platform.
 * Run: npx tsx test/seed-reviews.ts
 */
import { getDb, saveChallengeReview } from '../packages/db/dist/index.js';

const db = getDb();
const AID = 'assess-e2e-20260220';

async function seed() {
  // ═══════════════════════════════════════════════════════════════
  // DISCOVERY REVIEWS — 3 rounds, ends PASSED
  // ═══════════════════════════════════════════════════════════════

  // Round 1: Baseline — lots of gaps found
  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'discovery',
    round: 1,
    status: 'in_progress',
    confidence_score: 62,
    score_breakdown: { completeness: 70, consistency: 75, plausibility: 60, currency: 50, risk_coverage: 55 },
    acceptance_criteria_met: {
      completeness: false,
      consistency: true,
      plausibility: false,
      currency: false,
      risk_coverage: false,
    },
    challenges: [
      {
        id: 'DISC-CH-001',
        category: 'completeness',
        severity: 'high',
        description: "6 discovery answers have 'unknown' confidence across caching (eviction_policy), database (databases list), integrations (integration details), monitoring (custom_dashboards), networking (vpn_throughput), and storage (blob_provider_module). These unknowns feed directly into estimate assumptions.",
        data_reference: 'discovery.caching.eviction_policy, discovery.database.databases, discovery.integrations.integrations, discovery.monitoring.custom_dashboards, discovery.networking.vpn_throughput, discovery.storage.blob_provider_module',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 8,
      },
      {
        id: 'DISC-CH-002',
        category: 'plausibility',
        severity: 'high',
        description: 'Database total_size_gb of 120GB for 11 databases seems plausible, but largest_db_gb of 45GB (assumed xDB collection) should be verified. A 500K-2M contact xDB on SQL Server 2019 typically ranges 20-80GB depending on facets and interaction history.',
        data_reference: 'discovery.database.total_size_gb, discovery.database.largest_db_gb, discovery.xconnect.estimated_contacts',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 6,
      },
      {
        id: 'DISC-CH-003',
        category: 'currency',
        severity: 'medium',
        description: 'No Sitecore version captured. Topology is XP+EXM, but version (9.x vs 10.x) significantly affects migration — 10.x has container support, different Identity Server config, and serialization formats.',
        data_reference: 'assessment.sitecore_version (empty)',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 7,
      },
      {
        id: 'DISC-CH-004',
        category: 'completeness',
        severity: 'medium',
        description: "Integration dimension lists 3 integrations (Salesforce, Akeneo, Bynder) but detail answer is null. Missing: auth methods, data flow direction, sync frequency, error handling, data volume.",
        data_reference: 'discovery.integrations.integrations (null)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 5,
      },
      {
        id: 'DISC-CH-005',
        category: 'risk_coverage',
        severity: 'medium',
        description: 'No content authoring workflow data — number of editors, workflows, publishing targets, language versions. These drive testing scope and change management.',
        data_reference: 'Missing dimension: content_authoring',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'DISC-CH-006',
        category: 'consistency',
        severity: 'low',
        description: 'SSL dimension shows 3 certificates but ssl_tls dimension shows 30. These overlap — discrepancy needs reconciliation.',
        data_reference: 'discovery.ssl.certificate_count (3), discovery.ssl_tls.certificate_count (30)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 3,
      },
      {
        id: 'DISC-CH-007',
        category: 'plausibility',
        severity: 'low',
        description: 'ZooKeeper ensemble of 3 nodes for only 2 Solr nodes seems over-provisioned. Worth confirming ZooKeeper is a separate cluster vs. embedded.',
        data_reference: 'discovery.search.zookeeper_count (3), discovery.search.node_count (2)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 2,
      },
    ],
    findings: [
      {
        challenge_id: 'DISC-CH-002',
        finding: 'Sitecore xDB on SQL Server: collection database size depends heavily on interaction history retention. With default 90-day retention and 500K-2M contacts, 20-60GB is typical. 45GB is within plausible range.',
        source: 'Sitecore documentation',
        source_url: 'https://doc.sitecore.com/xp/en/developers/latest/sitecore-experience-platform/xdb-collection-database.html',
        verified_date: '2026-02-21',
        recommendation: 'Plausible but should verify via sp_spaceused on the actual xDB collection databases.',
        data_update_suggested: false,
      },
      {
        challenge_id: 'DISC-CH-003',
        finding: 'Sitecore 10.x introduced breaking changes to Identity Server (standalone IdentityServer4 → integrated), container deployment support, and Sitecore CLI for serialization. Version identification is critical for migration path.',
        source: 'Sitecore release notes',
        source_url: 'https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform.aspx',
        verified_date: '2026-02-21',
        recommendation: 'Must capture Sitecore version before proceeding. Check CM instance web.config or /sitecore/shell/sitecore.version.xml.',
        data_update_suggested: true,
      },
    ],
    summary: 'Initial baseline review of discovery data. 17 dimensions captured with solid infrastructure coverage. Key concerns: 6 unknown answers feeding directly into assumptions, missing Sitecore version, incomplete integration details, and no content authoring data. SSL certificate count inconsistency between ssl (3) and ssl_tls (30) dimensions. Score of 62% reflects infrastructure completeness but gaps in application detail.',
    completed_at: '2026-02-21T10:15:00Z',
  });

  // Round 2: Research findings improve plausibility and currency
  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'discovery',
    round: 2,
    status: 'in_progress',
    confidence_score: 76,
    score_breakdown: { completeness: 78, consistency: 82, plausibility: 78, currency: 68, risk_coverage: 70 },
    acceptance_criteria_met: {
      completeness: false,
      consistency: true,
      plausibility: true,
      currency: false,
      risk_coverage: false,
    },
    challenges: [
      {
        id: 'DISC-CH-001',
        category: 'completeness',
        severity: 'high',
        description: '6 unknown answers remain. VPN throughput and blob provider module are highest-impact unknowns.',
        data_reference: 'Same 6 unknowns from round 1',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 5,
      },
      {
        id: 'DISC-CH-002',
        category: 'plausibility',
        severity: 'high',
        description: 'Database size 45GB for xDB collection confirmed plausible by research.',
        data_reference: 'discovery.database.largest_db_gb',
        status: 'resolved',
        resolution: 'Research confirmed 45GB is within expected range for 500K-2M contacts on SQL Server with default retention.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'DISC-CH-003',
        category: 'currency',
        severity: 'medium',
        description: 'Sitecore version still not captured. Research shows version-specific migration paths differ significantly.',
        data_reference: 'assessment.sitecore_version',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 5,
      },
      {
        id: 'DISC-CH-004',
        category: 'completeness',
        severity: 'medium',
        description: 'Integration details still null. At minimum need auth mechanism and sync direction per integration.',
        data_reference: 'discovery.integrations.integrations',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'DISC-CH-005',
        category: 'risk_coverage',
        severity: 'medium',
        description: 'Content authoring workflow scope still unmapped.',
        data_reference: 'Missing dimension',
        status: 'accepted',
        resolution: 'Accepted: content authoring complexity will be captured as an assumption in analysis. Not blocking for discovery.',
        researcher_needed: false,
        score_impact: 2,
      },
      {
        id: 'DISC-CH-006',
        category: 'consistency',
        severity: 'low',
        description: 'SSL certificate discrepancy.',
        data_reference: 'ssl vs ssl_tls dimensions',
        status: 'resolved',
        resolution: 'ssl dimension tracks wildcard certificates (3). ssl_tls dimension was a supplementary capture including all individual cert bindings across IIS (30). Both are correct at different granularity.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'DISC-CH-007',
        category: 'plausibility',
        severity: 'low',
        description: 'ZooKeeper node count.',
        data_reference: 'discovery.search.zookeeper_count',
        status: 'resolved',
        resolution: 'Standard SolrCloud practice is ZK ensemble of 3 regardless of Solr node count, for quorum. This is correct.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'DISC-CH-008',
        category: 'currency',
        severity: 'medium',
        description: 'Windows Server 2019 is approaching end of mainstream support (Jan 2024 already passed). Migration to Azure should target Windows Server 2022 or consider containerized deployment if Sitecore 10.x.',
        data_reference: 'discovery.compute.os_version',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 3,
      },
    ],
    findings: [
      {
        challenge_id: 'DISC-CH-001',
        finding: "AWS VPN site-to-site typical throughput is 1.25 Gbps per tunnel. For Sitecore CM/CD workloads, 100-300 Mbps sustained is typical. Azure VPN Gateway Standard SKU matches at 650 Mbps.",
        source: 'AWS VPN documentation',
        source_url: 'https://docs.aws.amazon.com/vpn/latest/s2svpn/vpn-limits.html',
        verified_date: '2026-02-21',
        recommendation: "VPN throughput unknown is low-risk; Azure Standard VPN Gateway will likely suffice. Flag for validation but don't block.",
        data_update_suggested: false,
      },
      {
        challenge_id: 'DISC-CH-008',
        finding: 'Windows Server 2019 mainstream support ended January 9, 2024. Extended support runs until January 9, 2029. Azure does not charge extra for extended security updates for WS2019 when running on Azure VMs.',
        source: 'Microsoft lifecycle policy',
        source_url: 'https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2019',
        verified_date: '2026-02-21',
        recommendation: 'WS2019 on Azure gets free ESU — no urgency to upgrade OS during migration. Can be a post-migration optimization.',
        data_update_suggested: false,
      },
    ],
    summary: 'Round 2 improved score from 62% to 76% (+14 points). Three challenges resolved (xDB size plausibility, SSL consistency, ZooKeeper count). Content authoring gap accepted as deferred to analysis assumptions. Remaining open: 6 unknown answers, missing Sitecore version, incomplete integration details, and OS version currency. Research confirmed VPN throughput is low-risk and WS2019 gets free ESU on Azure.',
    completed_at: '2026-02-21T10:45:00Z',
  });

  // Round 3: Passes threshold
  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'discovery',
    round: 3,
    status: 'passed',
    confidence_score: 84,
    score_breakdown: { completeness: 82, consistency: 90, plausibility: 85, currency: 78, risk_coverage: 82 },
    acceptance_criteria_met: {
      completeness: true,
      consistency: true,
      plausibility: true,
      currency: true,
      risk_coverage: true,
    },
    challenges: [
      {
        id: 'DISC-CH-001',
        category: 'completeness',
        severity: 'high',
        description: '6 unknown answers remain but are appropriately tracked as assumptions.',
        data_reference: 'Same 6 unknowns',
        status: 'accepted',
        resolution: 'All 6 unknowns are tracked as formal assumptions (ASMP-005 through ASMP-011) with defined validation methods. Acceptable for discovery completeness.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'DISC-CH-003',
        category: 'currency',
        severity: 'medium',
        description: 'Sitecore version still missing from assessment record.',
        data_reference: 'assessment.sitecore_version',
        status: 'accepted',
        resolution: 'Version must be captured before analysis phase. Added as gate condition. Assessment topology (XP+EXM) constrains version to 9.x or 10.x.',
        researcher_needed: false,
        score_impact: 2,
      },
      {
        id: 'DISC-CH-004',
        category: 'completeness',
        severity: 'medium',
        description: 'Integration details still incomplete.',
        data_reference: 'discovery.integrations.integrations',
        status: 'accepted',
        resolution: 'Integration count (3) and names confirmed. Detailed per-integration audit deferred to analysis where it informs the custom_integration component estimate.',
        researcher_needed: false,
        score_impact: 1,
      },
      {
        id: 'DISC-CH-008',
        category: 'currency',
        severity: 'medium',
        description: 'Windows Server 2019 end-of-mainstream-support.',
        data_reference: 'discovery.compute.os_version',
        status: 'resolved',
        resolution: 'Azure provides free ESU for WS2019. OS upgrade is a post-migration optimization, not a migration blocker.',
        researcher_needed: false,
        score_impact: 0,
      },
    ],
    findings: [
      {
        challenge_id: 'DISC-CH-003',
        finding: 'Sitecore XP+EXM on EC2 with Identity Server as a separate role is consistent with Sitecore 9.1+ or 10.x deployment. The EC2 t3.medium for Identity Server suggests lower traffic, typical of staff-only SSO scenarios.',
        source: 'Sitecore installation guide',
        source_url: 'https://doc.sitecore.com/xp/en/developers/latest/sitecore-experience-platform/install-sitecore-xp.html',
        verified_date: '2026-02-21',
        recommendation: 'Architecture is consistent with 9.1-10.3 range. Version will be confirmed as gate condition for analysis phase.',
        data_update_suggested: false,
      },
    ],
    summary: 'Discovery review PASSED at 84%. All remaining open items have been formally accepted with documented rationale: 6 unknowns tracked as assumptions with validation methods, Sitecore version gated for analysis phase, integration details deferred to analysis. No unresolved critical or high-severity challenges. Discovery data provides sufficient foundation for analysis phase.',
    completed_at: '2026-02-21T11:10:00Z',
  });

  // ═══════════════════════════════════════════════════════════════
  // ANALYSIS REVIEWS — 2 rounds, ends PASSED
  // ═══════════════════════════════════════════════════════════════

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'analysis',
    round: 1,
    status: 'in_progress',
    confidence_score: 68,
    score_breakdown: { completeness: 75, consistency: 80, plausibility: 65, currency: 60, risk_coverage: 62 },
    acceptance_criteria_met: {
      completeness: false,
      consistency: true,
      plausibility: false,
      currency: false,
      risk_coverage: false,
    },
    challenges: [
      {
        id: 'ANAL-CH-001',
        category: 'risk_coverage',
        severity: 'high',
        description: '8 risks identified but none address Sitecore licensing implications of AWS-to-Azure move. Sitecore cloud licensing may require renegotiation when changing hosting provider, especially for XP+EXM topology.',
        data_reference: 'analysis.risks (missing licensing risk)',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 7,
      },
      {
        id: 'ANAL-CH-002',
        category: 'plausibility',
        severity: 'high',
        description: 'RISK-002 estimates 40 hours for EXM IP warming, but IP warming for 200K/month volume across 2 IPs is typically 4-6 weeks of effort. The 40h seems to conflate calendar time with effort hours. Effort should be ~15-20h monitoring + configuration; the rest is wait time.',
        data_reference: 'analysis.risks[RISK-002].estimated_hours_impact (40)',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 5,
      },
      {
        id: 'ANAL-CH-003',
        category: 'completeness',
        severity: 'medium',
        description: 'Dependency chains show 5 chains but miss the search→xconnect dependency. SolrCloud hosts xDB search indexes; if Solr migration fails, xConnect search won\'t function.',
        data_reference: 'analysis.dependency_chains',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'ANAL-CH-004',
        category: 'plausibility',
        severity: 'medium',
        description: 'Database multiplier stack: xdb_large (1.5×) × ha_db (1.4×) × multi_env (1.3×) = 2.73× on 132 base hours = 360h. With 20h gotcha, total is 380h. The multiplicative stacking may be overly aggressive — these multipliers measure partially overlapping complexity.',
        data_reference: 'analysis.active_multipliers for database_single component',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 6,
      },
      {
        id: 'ANAL-CH-005',
        category: 'risk_coverage',
        severity: 'medium',
        description: 'No risk captured for Sitecore content freeze / cutover content authoring. During cutover weekend, content authors cannot publish. If cutover extends, this impacts content operations.',
        data_reference: 'analysis.risks (missing cutover risk)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 3,
      },
      {
        id: 'ANAL-CH-006',
        category: 'consistency',
        severity: 'low',
        description: 'Risk cluster "Data Integrity" includes ASMP-001 (database size) which has already been validated. Cluster combined_widening_hours should be reduced by ASMP-001\'s 12h widening.',
        data_reference: 'analysis.risk_clusters.Data_Integrity.combined_widening_hours (40)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 2,
      },
    ],
    findings: [
      {
        challenge_id: 'ANAL-CH-001',
        finding: 'Sitecore subscription licensing (post-2020 model) is infrastructure-agnostic — tied to page views/contacts, not hosting provider. Legacy perpetual licenses may have hosting restrictions. Need to verify license type.',
        source: 'Sitecore licensing FAQ',
        source_url: 'https://www.sitecore.com/company/news-events/press-releases/2020/sitecore-launches-flexible-licensing',
        verified_date: '2026-02-21',
        recommendation: 'Add licensing verification as a risk item. If subscription license, no impact. If perpetual, may require Sitecore approval for cloud migration.',
        data_update_suggested: true,
      },
      {
        challenge_id: 'ANAL-CH-002',
        finding: 'SendGrid IP warmup for 200K/month typically takes 4-6 weeks. Daily monitoring is ~30 min/day (15-20h total), plus initial configuration (4-6h). Total effort is 20-25h, not 40h. The 40h may include contingency for deliverability issues.',
        source: 'SendGrid IP warmup guide',
        source_url: 'https://docs.sendgrid.com/ui/sending-email/ip-warmup-for-the-new-ip-address',
        verified_date: '2026-02-21',
        recommendation: 'Revise RISK-002 hours impact from 40 to 25, with remaining 15h as contingency clearly labeled.',
        data_update_suggested: true,
      },
      {
        challenge_id: 'ANAL-CH-004',
        finding: 'In practice, multiplier stacking rarely compounds linearly. Industry benchmarks suggest applying diminishing returns: 1st multiplier at full, 2nd at 80%, 3rd at 60%. This would reduce database component from 380h to ~310h.',
        source: 'Software estimation research',
        source_url: null,
        verified_date: '2026-02-21',
        recommendation: 'Note the multiplicative stacking concern in risk register. Consider capping combined multiplier effect at 2.5× for any single component in the estimate.',
        data_update_suggested: true,
      },
    ],
    summary: 'Analysis baseline at 68%. Risk register covers core technical risks well but misses licensing and cutover content freeze. EXM IP warming hours impact (40h) appears inflated — research suggests 20-25h effort. Database multiplier stacking at 2.73× may be overly aggressive. Dependency chain missing search→xconnect link. ASMP-001 validated but risk cluster not updated.',
    completed_at: '2026-02-21T12:30:00Z',
  });

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'analysis',
    round: 2,
    status: 'passed',
    confidence_score: 83,
    score_breakdown: { completeness: 85, consistency: 88, plausibility: 82, currency: 75, risk_coverage: 80 },
    acceptance_criteria_met: {
      completeness: true,
      consistency: true,
      plausibility: true,
      currency: true,
      risk_coverage: true,
    },
    challenges: [
      {
        id: 'ANAL-CH-001',
        category: 'risk_coverage',
        severity: 'high',
        description: 'Licensing risk for cloud migration.',
        data_reference: 'analysis.risks',
        status: 'accepted',
        resolution: 'Research shows subscription licensing is infrastructure-agnostic. Noted for verification during planning phase. Not a blocking risk for analysis.',
        researcher_needed: false,
        score_impact: 2,
      },
      {
        id: 'ANAL-CH-002',
        category: 'plausibility',
        severity: 'high',
        description: 'EXM IP warming hours overestimate.',
        data_reference: 'analysis.risks[RISK-002]',
        status: 'resolved',
        resolution: 'Acknowledged: 40h includes buffer. Estimate phase will reflect 25h base + 15h contingency separately in gotcha_hours.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'ANAL-CH-003',
        category: 'completeness',
        severity: 'medium',
        description: 'Missing search→xconnect dependency.',
        data_reference: 'analysis.dependency_chains',
        status: 'resolved',
        resolution: 'Added solr_cloud → xconnect_xdb soft dependency to chain model.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'ANAL-CH-004',
        category: 'plausibility',
        severity: 'medium',
        description: 'Multiplicative stacking concern on database component.',
        data_reference: 'analysis.active_multipliers',
        status: 'accepted',
        resolution: 'Acknowledged as conservative. Estimate phase will note this as a potential over-estimate. Combined multiplier of 2.73× retained as-is since database migration is highest-risk component — conservatism is appropriate here.',
        researcher_needed: false,
        score_impact: 1,
      },
      {
        id: 'ANAL-CH-005',
        category: 'risk_coverage',
        severity: 'medium',
        description: 'Missing cutover content freeze risk.',
        data_reference: 'analysis.risks',
        status: 'resolved',
        resolution: 'Cutover execution component (16h) implicitly covers content freeze window. Risk is operational, not technical. Added note to cutover runbook template requirements.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'ANAL-CH-006',
        category: 'consistency',
        severity: 'low',
        description: 'Risk cluster widening hours not updated for validated ASMP-001.',
        data_reference: 'analysis.risk_clusters.Data_Integrity',
        status: 'resolved',
        resolution: 'ASMP-001 validated — widening hours should reduce from 40 to 28. Noted for estimate recalculation.',
        researcher_needed: false,
        score_impact: 0,
      },
    ],
    findings: [],
    summary: 'Analysis review PASSED at 83% (up from 68%). All critical findings resolved or accepted with documented rationale. Licensing risk accepted as low-probability given subscription model. EXM hours will be split into base + contingency in estimate. Database multiplier stacking retained as appropriate conservatism for highest-risk component. Dependency chain updated. Analysis is ready to support estimate generation.',
    completed_at: '2026-02-21T13:15:00Z',
  });

  // ═══════════════════════════════════════════════════════════════
  // ESTIMATE REVIEWS — 3 rounds, ends CONDITIONAL_PASS
  // ═══════════════════════════════════════════════════════════════

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'estimate',
    round: 1,
    status: 'in_progress',
    confidence_score: 58,
    score_breakdown: { completeness: 72, consistency: 68, plausibility: 50, currency: 55, risk_coverage: 50 },
    acceptance_criteria_met: {
      completeness: false,
      consistency: false,
      plausibility: false,
      currency: false,
      risk_coverage: false,
    },
    challenges: [
      {
        id: 'EST-CH-001',
        category: 'plausibility',
        severity: 'critical',
        description: 'Database migration at 380h (36% of total) seems disproportionate for 120GB across 11 databases. Industry benchmarks for SQL Server → Azure SQL MI migration of this scale typically range 120-200h including testing.',
        data_reference: 'estimate.phases.phase_2_data.components.database_single.final_hours (380)',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 12,
      },
      {
        id: 'EST-CH-002',
        category: 'plausibility',
        severity: 'high',
        description: 'Total 1046h (manual scenario) for a single-topology Sitecore XP+EXM migration is at the high end. Comparable AWS→Azure Sitecore migrations typically range 600-900h for this complexity level.',
        data_reference: 'estimate.total_expected_hours (1046)',
        status: 'open',
        resolution: null,
        researcher_needed: true,
        score_impact: 8,
      },
      {
        id: 'EST-CH-003',
        category: 'risk_coverage',
        severity: 'high',
        description: 'Assumption widening of 96h is significant (9% of total). Only 1 of 12 assumptions validated. The pessimistic scenario at 1456h is 39% above expected — this range may alarm stakeholders without adequate context.',
        data_reference: 'estimate.assumption_widening_hours (96), estimate.totals.without_ai.pessimistic (1456)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 5,
      },
      {
        id: 'EST-CH-004',
        category: 'completeness',
        severity: 'medium',
        description: 'No training or knowledge transfer component. Post-migration, the Azure operations team needs handover documentation and possibly runbook walkthroughs.',
        data_reference: 'estimate.phases (missing training component)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'EST-CH-005',
        category: 'consistency',
        severity: 'medium',
        description: 'Infrastructure engineer at 372h (36% of total) but no Azure-specific skills assessment. If the existing team lacks Azure experience, ramp-up time should be factored in or an Azure specialist should be added.',
        data_reference: 'estimate.total_by_role.infrastructure_engineer (372)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'EST-CH-006',
        category: 'currency',
        severity: 'medium',
        description: 'AI savings estimates assume current tool capabilities. Claude Code and GitHub Copilot savings of 3-5h per component may be conservative or optimistic depending on infrastructure-as-code maturity.',
        data_reference: 'estimate.phases various ai_alternatives',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 3,
      },
    ],
    findings: [
      {
        challenge_id: 'EST-CH-001',
        finding: 'Azure Database Migration Service (DMS) benchmarks show SQL Server → Azure SQL MI migration rates of 200-500 GB/hour for online migrations. For 120GB with 11 databases, bulk migration takes 1-4 hours. However, Sitecore database migration includes: schema validation, collation verification, xDB shard testing, and post-migration index rebuilds.',
        source: 'Azure DMS documentation',
        source_url: 'https://learn.microsoft.com/en-us/azure/dms/tutorial-sql-server-to-managed-instance',
        verified_date: '2026-02-21',
        recommendation: 'The 380h includes multiplier stacking (2.73×). Raw migration is fast, but the hours cover multi-environment deployment, xDB validation, and HA testing. Recommend breaking down the 380h into sub-tasks for transparency.',
        data_update_suggested: false,
      },
      {
        challenge_id: 'EST-CH-002',
        finding: 'Comparable Sitecore XP+EXM AWS→Azure migrations: (1) Similar scope 4-CD topology took 720h, (2) Smaller 2-CD setup took 480h, (3) Large 8-CD with 5M contacts took 1400h. Contoso at 1046h with 4 CDs and complex xDB is within range but on the higher side.',
        source: 'Industry benchmarks',
        source_url: null,
        verified_date: '2026-02-21',
        recommendation: 'Total is defensible given multiplier profile and assumption load. The 884h AI-assisted scenario is more in line with benchmarks for this complexity.',
        data_update_suggested: false,
      },
    ],
    summary: 'Estimate baseline at 58%. Critical concern: database component at 380h (36% of total) driven by aggressive multiplier stacking. Total 1046h is at the high end of benchmarks for this topology. Missing training/KT component. High infrastructure engineer allocation without Azure skills assessment. Assumption widening at 96h with only 1/12 assumptions validated creates wide pessimistic range.',
    completed_at: '2026-02-21T14:00:00Z',
  });

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'estimate',
    round: 2,
    status: 'in_progress',
    confidence_score: 70,
    score_breakdown: { completeness: 78, consistency: 75, plausibility: 68, currency: 62, risk_coverage: 66 },
    acceptance_criteria_met: {
      completeness: false,
      consistency: true,
      plausibility: false,
      currency: false,
      risk_coverage: false,
    },
    challenges: [
      {
        id: 'EST-CH-001',
        category: 'plausibility',
        severity: 'critical',
        description: 'Database 380h — research confirms raw migration is fast. The inflated hours come from multiplier stacking. Partially addressed by analysis review acceptance of conservative approach.',
        data_reference: 'estimate.phases.phase_2_data.components.database_single',
        status: 'accepted',
        resolution: 'Multiplier stacking is acknowledged as conservative per analysis review. The 380h includes multi-environment replication, xDB validation, HA failover testing, and collation verification across 11 databases. Accepted with note that actual hours may be 20-30% lower.',
        researcher_needed: false,
        score_impact: 3,
      },
      {
        id: 'EST-CH-002',
        category: 'plausibility',
        severity: 'high',
        description: 'Total hours within benchmark range per research.',
        data_reference: 'estimate.total_expected_hours',
        status: 'resolved',
        resolution: 'Industry benchmarks confirm 1046h is within range. AI-assisted scenario at 884h aligns well with median benchmark. Conservative total gives buffer for the 11 unvalidated assumptions.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'EST-CH-003',
        category: 'risk_coverage',
        severity: 'high',
        description: 'Wide pessimistic range needs stakeholder context.',
        data_reference: 'estimate.totals',
        status: 'accepted',
        resolution: 'Client summary narrative already explains: "Validating top 5 assumptions would reduce pessimistic by ~54h and raise confidence to ~82%." This provides adequate context. The range is wide by design — it reflects genuine uncertainty.',
        researcher_needed: false,
        score_impact: 1,
      },
      {
        id: 'EST-CH-004',
        category: 'completeness',
        severity: 'medium',
        description: 'Missing training/KT component.',
        data_reference: 'estimate.phases',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 3,
      },
      {
        id: 'EST-CH-005',
        category: 'consistency',
        severity: 'medium',
        description: 'Infrastructure engineer Azure skills gap.',
        data_reference: 'estimate.total_by_role',
        status: 'accepted',
        resolution: 'Azure skills assessment is a staffing/planning concern, not an estimate gap. The hours assume a qualified Azure engineer. Noted in risk register as operational risk.',
        researcher_needed: false,
        score_impact: 1,
      },
      {
        id: 'EST-CH-006',
        category: 'currency',
        severity: 'medium',
        description: 'AI savings tool maturity uncertainty.',
        data_reference: 'estimate.ai_alternatives',
        status: 'accepted',
        resolution: 'AI savings are presented as a separate scenario (884h AI-assisted vs 1046h manual). Client can choose which scenario to plan against. Savings are conservatively capped at 50% per component.',
        researcher_needed: false,
        score_impact: 1,
      },
    ],
    findings: [],
    summary: 'Estimate improved to 70% (from 58%). Database hours accepted as conservative but defensible. Total hours within industry benchmarks. Pessimistic range explained in client summary narrative. Still missing training/KT component. AI savings and skills gap concerns accepted with documented rationale.',
    completed_at: '2026-02-21T14:45:00Z',
  });

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'estimate',
    round: 3,
    status: 'conditional_pass',
    confidence_score: 76,
    score_breakdown: { completeness: 80, consistency: 82, plausibility: 75, currency: 68, risk_coverage: 72 },
    acceptance_criteria_met: {
      completeness: true,
      consistency: true,
      plausibility: true,
      currency: false,
      risk_coverage: true,
    },
    challenges: [
      {
        id: 'EST-CH-001',
        category: 'plausibility',
        severity: 'critical',
        description: 'Database hours accepted as conservative.',
        data_reference: 'estimate.phases.phase_2_data.components.database_single',
        status: 'accepted',
        resolution: 'Accepted with documented conservatism note. Actual may be 20-30% lower.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'EST-CH-004',
        category: 'completeness',
        severity: 'medium',
        description: 'Training/KT still not in estimate.',
        data_reference: 'estimate.phases',
        status: 'accepted',
        resolution: 'Training and knowledge transfer (estimated 16-24h) typically handled as a separate SOW item or included in project management allocation. The 40h project management component has capacity to absorb KT activities. Accepted — not a gap in the migration estimate itself.',
        researcher_needed: false,
        score_impact: 0,
      },
    ],
    findings: [],
    summary: 'Estimate review CONDITIONAL PASS at 76%. All challenges resolved or accepted. Score plateaued (+6 points from round 2). Conditional because currency score (68%) remains below 80% threshold — driven by 11 unvalidated assumptions and AI tool maturity uncertainty. No critical or high challenges remain open. Estimate is usable for planning with the documented caveats.',
    completed_at: '2026-02-21T15:15:00Z',
  });

  // ═══════════════════════════════════════════════════════════════
  // REFINE REVIEWS — 2 rounds, ends PASSED
  // ═══════════════════════════════════════════════════════════════

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'refine',
    round: 1,
    status: 'in_progress',
    confidence_score: 72,
    score_breakdown: { completeness: 78, consistency: 80, plausibility: 70, currency: 62, risk_coverage: 68 },
    acceptance_criteria_met: {
      completeness: false,
      consistency: true,
      plausibility: false,
      currency: false,
      risk_coverage: false,
    },
    challenges: [
      {
        id: 'REF-CH-001',
        category: 'completeness',
        severity: 'high',
        description: 'Only 1 of 12 assumptions (ASMP-001, database size) has been validated. The refine phase should prioritize validation of the top 5 highest-impact assumptions: ASMP-002 (xDB contacts), ASMP-012 (custom facets), ASMP-004 (EXM volume), ASMP-005 (AWS SDK usage), and ASMP-009 (DB collation).',
        data_reference: 'analysis.assumptions[*].validation_status',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 8,
      },
      {
        id: 'REF-CH-002',
        category: 'risk_coverage',
        severity: 'high',
        description: 'Scope exclusions applied but no documentation of what was excluded and why. If components were excluded, the rationale should be recorded for audit trail.',
        data_reference: 'scope_exclusions',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 5,
      },
      {
        id: 'REF-CH-003',
        category: 'plausibility',
        severity: 'medium',
        description: 'Client summary recommends 884h (AI-assisted) as the primary estimate. This assumes all recommended AI tools are adopted. If the client has constraints on tool adoption (security policies, licensing), the recommendation should note fallback to manual (1046h).',
        data_reference: 'estimate.client_summary.recommended_hours (884)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'REF-CH-004',
        category: 'currency',
        severity: 'medium',
        description: 'Estimate confidence at 68% — below the 80% threshold typically expected for client-facing proposals. The refine phase should aim to raise this via assumption validation.',
        data_reference: 'estimate.confidence_score (68)',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 4,
      },
      {
        id: 'REF-CH-005',
        category: 'consistency',
        severity: 'low',
        description: 'Phase durations are estimates (e.g., "3-4 weeks") but not tied to specific resource allocation. Without FTE mapping, the durations are aspirational rather than plannable.',
        data_reference: 'estimate.phases[*].duration',
        status: 'open',
        resolution: null,
        researcher_needed: false,
        score_impact: 2,
      },
    ],
    findings: [
      {
        challenge_id: 'REF-CH-001',
        finding: 'Assumption validation priority matrix based on pessimistic_widening_hours: ASMP-012 (12h), ASMP-001 (12h, already validated), ASMP-004 (12h), ASMP-005 (10h), ASMP-002 (8h). Top 4 unvalidated total 42h widening — validating these would reduce pessimistic range significantly.',
        source: 'Analysis data',
        source_url: null,
        verified_date: '2026-02-21',
        recommendation: 'Provide client with the validation checklist: each assumption includes a specific validation_method. Prioritize the top 4 by widening hours.',
        data_update_suggested: false,
      },
    ],
    summary: 'Refine baseline at 72%. Primary concern: 11 of 12 assumptions unvalidated, keeping confidence at 68%. Scope exclusion rationale should be documented. Client-facing recommendation of 884h (AI-assisted) needs fallback context. Phase durations lack FTE mapping.',
    completed_at: '2026-02-21T16:00:00Z',
  });

  await saveChallengeReview(db, {
    assessment_id: AID,
    step: 'refine',
    round: 2,
    status: 'passed',
    confidence_score: 82,
    score_breakdown: { completeness: 85, consistency: 86, plausibility: 82, currency: 75, risk_coverage: 80 },
    acceptance_criteria_met: {
      completeness: true,
      consistency: true,
      plausibility: true,
      currency: false,
      risk_coverage: true,
    },
    challenges: [
      {
        id: 'REF-CH-001',
        category: 'completeness',
        severity: 'high',
        description: 'Assumption validation progress.',
        data_reference: 'analysis.assumptions',
        status: 'accepted',
        resolution: 'Validation checklist generated with prioritized assumptions and specific methods. Client has been provided the checklist. Validation is a client-side action — the refine phase has done what it can to facilitate. Accepted with caveat that confidence will remain at 68% until client validates.',
        researcher_needed: false,
        score_impact: 2,
      },
      {
        id: 'REF-CH-002',
        category: 'risk_coverage',
        severity: 'high',
        description: 'Scope exclusion documentation.',
        data_reference: 'scope_exclusions',
        status: 'resolved',
        resolution: 'Scope exclusions are tracked in the scope-exclusions data with per-component flags. The refine page displays which components are excluded. Adequate for traceability.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'REF-CH-003',
        category: 'plausibility',
        severity: 'medium',
        description: 'AI-assisted recommendation fallback.',
        data_reference: 'estimate.client_summary',
        status: 'resolved',
        resolution: 'Client summary includes range_narrative that explicitly states both manual (1046h) and AI-assisted (884h) scenarios with confidence context. Adequate fallback documentation.',
        researcher_needed: false,
        score_impact: 0,
      },
      {
        id: 'REF-CH-004',
        category: 'currency',
        severity: 'medium',
        description: 'Confidence below 80% threshold.',
        data_reference: 'estimate.confidence_score',
        status: 'accepted',
        resolution: 'Confidence of 68% is a factual reflection of the assumption validation state. The narrative explains that validating top 5 assumptions would raise it to ~82%. This is transparent — not a gap in the refine process.',
        researcher_needed: false,
        score_impact: 1,
      },
      {
        id: 'REF-CH-005',
        category: 'consistency',
        severity: 'low',
        description: 'Phase duration FTE mapping.',
        data_reference: 'estimate.phases',
        status: 'accepted',
        resolution: 'FTE mapping is a deliverables/planning activity beyond the scope of the estimate refine. The estimate provides hours by role, which enables FTE calculation. Accepted as out of scope for refine.',
        researcher_needed: false,
        score_impact: 0,
      },
    ],
    findings: [],
    summary: 'Refine review PASSED at 82%. All challenges resolved or accepted. Assumption validation checklist created and prioritized. Scope exclusions adequately tracked. Client summary provides both manual and AI-assisted scenarios with confidence context. Currency score (75%) remains below 80% due to unvalidated assumptions, but this is a factual reflection, not a process gap. The assessment is ready for deliverable generation.',
    completed_at: '2026-02-21T16:30:00Z',
  });

  console.log('All reviews seeded successfully!');
  process.exit(0);
}

seed().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
